services:
  app:
    build:
      context: .
      target: ${APP_ENV:-prod}
    container_name: go-fridge-api
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "40000:40000" # expose for delve debugging (only used if debug build)
    depends_on:
      - db    
    networks:
      - fridge-network

  db:
    image: postgres:16
    container_name: fridge-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fridge-network

volumes:
  postgres_data: {}

networks:
  fridge-network:
    driver: bridge